export RESTIC_REPOSITORY="s3:https://s3.amazonaws.com/<bucketname>"
export AWS_ACCESS_KEY_ID="AKIXXXXXXXXXWD"
export AWS_SECRET_ACCESS_KEY="a/11Mzj8XXXXXXXXXXXNwzfqvJ"
export RESTIC_PASSWORD="4lXXXXXXXXm"
export AWS_DEFAULT_REGION="us-east-1"
